name: Publish to NPM
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install latest npm
        run: npm install -g npm@latest
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Publish to NPM
        run: npm publish